### ISSUE TITLE
some kind of output in terminal

### ISSUE THREAD

**Issue by GoogleCodeExporter** [dvschultz/rastertovector#1]
```
What steps will reproduce the problem?
1. open terminal
2. run : java -jar  runsxz.jar 
3. a wired output produced

What is the expected output? What do you see instead?

that is the output is see:
java.io.FileNotFoundException: gradient.properties (No such file or directory)
    at java.io.FileInputStream.open(Native Method)
    at java.io.FileInputStream.<init>(FileInputStream.java:137)
    at java.io.FileInputStream.<init>(FileInputStream.java:96)
    at com.sxz.GUI.Main.main(Main.java:73)


Please provide any additional information below.
i use linux ubuntu hardy heron with latest updates

```

Original issue reported on code.google.com by `blazee...@gmail.com` on 12 Sep 2008 at 4:03

**Comment by GoogleCodeExporter** [comment]
```
Thank you for trying out the application!

The program will work without the gradient.properties file, but I will improve 
the
code to not display the error message.  For now, a gradient.properties file is 
on the
download tab and can be placed in the same directory as the runsxz.jar file.  
This
will make the error message go away.
```

Original comment by `contact%...@gtempaccount.com` on 12 Sep 2008 at 5:19
